name: Deploy to ECS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify AWS region

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 536697260132.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, Tag, Push image to ECR
        run: |
          IMAGE_TAG=latest
          docker build -t singh-final-api:$IMAGE_TAG .
          docker tag singh-final-api:$IMAGE_TAG 536697260132.dkr.ecr.us-east-1.amazonaws.com/singh-final-api:$IMAGE_TAG
          docker push 536697260132.dkr.ecr.us-east-1.amazonaws.com/singh-final-api:$IMAGE_TAG

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: singh-api-service
          cluster: singh-cluster
          wait-for-service-stability: true
